### ISSUE TITLE
Return 404 if route not found

### ISSUE THREAD

**Issue by vladfaust** [tbrand/router.cr#13]
Currently if the route not found it doesn't touch the default response and returns 200 status code.

**Comment by vladfaust** [comment]
There are two possible variants:
1. Assuming that the handler may not not be the last in the row of server handlers:
```crystal
def call(context)
  if route_context = search_route(context)
    route_context.api.call(context, route_context.params)
  elsif !@next
    context.response.status_code = 404
    context.response.headers["Content-Type"] = "text/plain"
    context.response.puts "Not Found"
  end

  call_next(context) if @next
end
```
2. Or if the route handled, stop further executions (it's the traditional approach - routes are always on the top of middleware stack):
```crystal
def call(context)
  if route_context = search_route(context)
    route_context.api.call(context, route_context.params)
  else
    call_next(context)
  end
end
```

**Comment by tbrand** [comment]
The latter one seems good. I'll implement it.

**Comment by vladfaust** [comment]
I'm already doing this

**Comment by tbrand** [comment]
Published
