### ISSUE TITLE
Rename API to Action

### ISSUE THREAD

**Issue by vladfaust** [tbrand/router.cr#16]
When a server is accessed with a path, it idiomatically triggers something a.k.a. an action happens. My proposal is to replace API (`alias API = Proc(HTTP::Server::Context, Hash(String, String)`) with Action.

**Comment by tbrand** [comment]
Sounds good!

**Comment by tbrand** [comment]
@vladfaust Is it ok for you?

**Comment by vladfaust** [comment]
@tbrand lgtm :smile: 
FYI I currently use my own implementation which has this loc: `@@tree = Radix::Tree(ActionProc | Actions::Base.class).new`, and `Actions::Base` class:
```crystal
  module Actions
    abstract class Base
      private getter context, path_params

      def initialize(@context : HTTP::Server::Context, @path_params : Hash(String, String))
      end

      abstract def call

      def self.call(context, path_params)
        i = self.new(context, path_params)
        i.call
        i
      end
    end
  end
```
Works for me, but might be an overhead for router.cr.

According to the issue, I might suggest to rename it to ActionProc or something because in projects `Actions / Action` namespace would be usually reserved.
