### ISSUE TITLE
Add tests for TechEmpower Framework Benchmarks

### ISSUE THREAD

**Issue by faustinoaq** [tbrand/router.cr#18]
Hi @tbrand, I like router.cr as middleware.

Would be possible to add router.cr to https://github.com/TechEmpower/FrameworkBenchmarks ?

TFB have three categories:

1. Middlewares, like puma, nginx
2. Micro frameworks like Kemal, Sinatra, Flask
3. Full frameworks like Phoenix, Django, Amber.

I think router.cr can compete in the first category, What do you think?

Tests for crystal-raw: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Crystal/crystal

**Comment by tbrand** [comment]
Hi @faustinoaq 

I'm really honored!!
Agreed, router.cr should be in the first.

Should I send a PR for this? or could you add this?

Thanks!

**Comment by faustinoaq** [comment]
I would like you send the PR 😜

**Comment by tbrand** [comment]
💯

**Comment by faustinoaq** [comment]
👍 You should create a new entry on https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/.travis.yml#L39

and a new directory with `router.cr` files,

**Comment by faustinoaq** [comment]
I think `router.cr` is very similar to `crystal-raw` implementation on TFB, so I'm closing this

Reopen this if you want to :sweat_smile:
