### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [tbrand/router.cr#24]
Hello,

I've checked your project and it either:

* Has specs failed with the latest Crystal (0.26.1)
* Has no any specs to run so it cannot be validated to be up to date
* Has the latest commit dated more than a year ago

Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by stakach** [comment]
I’m using it as the core of spider-gazelle which still works - so happy to maintain if @tbrand has lost interest

**Comment by tbrand** [comment]
Yup. It's maintained. I'll fix for the latest crystal.

**Comment by tbrand** [comment]
Done. https://github.com/tbrand/router.cr/pull/25

Let me close this issue. Updated router.cr to v0.2.4.
https://github.com/tbrand/router.cr/releases/tag/v0.2.4

**Comment by vladfaust** [comment]
Note that you can set up daily/weekly tests on Travis so you'll receive a notification when the build begins to fail: https://docs.travis-ci.com/user/cron-jobs.

Thanks, @tbrand!
