### ISSUE TITLE
Parsing POST/GET params?

### ISSUE THREAD

**Issue by duanearnett** [tbrand/router.cr#35]
Is there an example for how to retrieve POST params from an HTML form? router.cr seems to ignore GET and POST params, only providing the params available in the URL (e.g., '/posts/:post_id').

Am I missing something? Or is that a limitation of this router framework?

**Comment by stakach** [comment]
Router.cr does not merge all the various sources of route params, query params, form body etc
So you have to obtain / parse / merge these yourself.

If you don't want to deal with all the complexities of doing all that then you could use https://spider-gazelle.net/ which is built on router.cr with all the bells and whistles added - lazily loaded in an attempt to maintain the lightweight performance.

**Comment by tbrand** [comment]
Great, please check spider-gazelle then. Thanks @stakach.
