### ISSUE TITLE
Handle parameters (GET-style) passed after the resource in the query string

### ISSUE THREAD

**Issue by RomanHargrave** [tbrand/router.cr#4]
Given the route specification `/:id` I should be able to request `/12345?param=value` and have 
the router break down the params as `{"id": "12345",  "param": "value"}`, instead the parameters are given as `{"id": "12345?param=value"}`.

**Comment by tbrand** [comment]
Oh that's a critical bug. I'll fix this. Thanks for the report:smile:

**Comment by RomanHargrave** [comment]
NP. I was actually about to check it out and separate params before you search the tree, but I'm moving a bit slow.
