### ISSUE TITLE
"routers" don't cooperate when combined

### ISSUE THREAD

**Issue by RomanHargrave** [tbrand/router.cr#7]
You should be able to combine multiple handlers that can handle different routes (e.g. a handler for /favicon.ico or a monitoring API, etc...)

`Route::RouteHandler#call(context)` raises an exception when it can't route rather than "passing the torch" to the next handler. This makes combining routers impossible.

**Comment by tbrand** [comment]
I agree. You say that stop raising exceptions even if the route not found, right?

**Comment by tbrand** [comment]
What do you think about this? https://github.com/tbrand/route.cr/pull/8

**Comment by RomanHargrave** [comment]
#8 is the way I went about it

**Comment by tbrand** [comment]
Got it. Merge that.
